# Generated by Django 4.0.6 on 2023-02-15 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userA', models.CharField(max_length=100)),
                ('userB', models.CharField(max_length=100)),
                ('active_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
