# Generated by Django 4.0.6 on 2023-02-15 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comment_comment_body_alter_likepost_post_id_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text_body', models.TextField()),
                ('name', models.CharField(default='user', max_length=30)),
                ('profile_img', models.ImageField(default='lobby-img.png', upload_to='msg_profiles')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
