# Generated by Django 4.0.6 on 2023-02-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmsg',
            name='profile_img',
        ),
    ]
