# Generated by Django 4.0.6 on 2022-11-21 17:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_id_user_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('caption', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
