# Generated by Django 4.0.6 on 2022-11-24 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_author_first_post_author_img_post_author_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(default='', max_length=100)),
                ('body_text', models.TextField()),
                ('time_sent', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
