# Generated by Django 4.0.6 on 2022-11-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text_img',
            field=models.ImageField(blank=True, upload_to='text_images'),
        ),
    ]
