# Generated by Django 4.0.6 on 2023-01-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_savepost_comment_no_of_saves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='no_of_saves',
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_saves',
            field=models.IntegerField(default=0),
        ),
    ]
