# Generated by Django 4.0.6 on 2023-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_comment_no_of_saves_post_no_of_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_img',
            field=models.ImageField(blank=True, upload_to='post_author_images'),
        ),
    ]
