# Generated by Django 4.0.6 on 2023-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_likecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
