# Generated by Django 4.0.6 on 2023-02-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comment_comment_body_alter_likepost_post_id_and_more'),
        ('lobby', '0004_lobbymsgs_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('joined_lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
