# Generated by Django 4.0.6 on 2023-02-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_lobby_no_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
    ]
