# Generated by Django 4.0.6 on 2023-02-14 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_member_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.UUIDField(default=uuid.UUID('fda7987a-2412-4a6c-8e06-a543abbe1094'), primary_key=True, serialize=False)),
                ('userA', models.CharField(max_length=30)),
                ('userB', models.CharField(max_length=30)),
            ],
        ),
    ]
