# Generated by Django 4.0.6 on 2023-02-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
